title: IMOP
description: "An Infrastructure Management Optimization Platform for the City of San Diego."
owner_name: Aditya Katre
github_username: adik1025
github_repo: "imop_frontend"
baseurl: "/imop_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
